# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'OWF Learn / TSTool'
pages:
- Introduction: index.md
#- Overview: overview.md
- Install TSTool: install-tstool.md
- Lessons:
  - '1 - Quick Start': '01-lesson-quick-start/lesson-quick-start.md'
  - '2 - Read CO HydroBase Web Service': '02-lesson-read-co-hydrobase-ws/lesson-read-co-hydrobase-ws.md'
- Resources: resources.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
#theme: readthedocs
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-qgis
site_description:  'Open Water Foundation Learn TSTool'
site_author:  'Open Water Foundation'
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  'Copyright Open Water Foundation'
# Extra options
# Use extra CSS to customize styles, based o
extra_css:
  - 'css/extra-material-theme.css'
