# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'Learn / TSTool'
nav:
- Home: index.md
- Install TSTool: install-tstool.md
- Lessons:
  - 'Overview': 'lessons/overview.md'
  - '1 - Quick Start': 'lessons/01-lesson-quick-start/lesson-quick-start.md'
  - '2 - Read CO HydroBase Web Service': 'lessons/02-lesson-read-co-hydrobase-ws/lesson-read-co-hydrobase-ws.md'
- Examples:
  - 'Overview': 'examples/overview.md'
- Resources: resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  'Copyright Open Water Foundation'
# Extra options
# Use extra CSS to customize styles, based o
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-tstool
site_author:  'Open Water Foundation'
site_description:  'Open Water Foundation Learn TSTool'
# ------------------------------------------------
# Use Material theme:
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.png'
